### ISSUE TITLE
Boto3 errors after updating from 0.19.0 to 0.19.3

### ISSUE THREAD

**Issue by woodmicha** [getsentry/sentry-python#925]
Getting errors on my services that write to s3 buckets after this update.  Error seems to be related to something called service_id.  Had to roll back to 0.19.0.

'ServiceModel' object has no attribute 'service_id' exception on line 74 of create_client.  We've not updated boto in a long time and are running the following:

boto3                               1.4.8
botocore                            1.8.12

**Comment by untitaker** [comment]
Duplicate of #920
