### ISSUE TITLE
V2.23.0: Potentially broken release?

### ISSUE THREAD

**Issue by mimre25** [getsentry/sentry-python#4139]
### How do you use Sentry?

Self-hosted/on-premise

### Version

2.23

### Steps to Reproduce

1. Upgrade sentry to 2.23
2. use `from sentry_sdk import *`

### Expected Result

The import should just work.

### Actual Result

```
E   AttributeError: module 'sentry_sdk' has no attribute '_experimental_logger.py'. Did you mean: '_experimental_logger'?
```

It worked fine with 2.22.

**Comment by antonpirker** [comment]
Hey @mimre25 just wanted to let you know that I yanked version `2.23.0` from PyPI and released a fixed version `2.23.1`.

Thanks again for the quick issue report!
