### ISSUE TITLE
Probable threading issue in uwsgi + django when upgrading to 1.13.0

### ISSUE THREAD

**Issue by firaskafri** [getsentry/sentry-python#1835]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.13.0

### Steps to Reproduce

In a k8s environment, with a python container that is running a django web app with uwsgi, we upgraded from 1.12.1 to 1.13.0 and started having issues with uwsgi process spawning.

uwsgi config are the default configurations with `--threads` + `--max-requests` enabled

The issue resolved after downgrading from 1.13.0 to 1.12.1 again.

### Expected Result

uwsgi must spawn and respawn new worker processes freely.

### Actual Result

Whenever a new uwsgi worker process is respawned or spawned, it hangs and never receives requests:
`spawned uWSGI worker 1 (pid: 24, cores: 1)` <----- hangs here

 When gdb is used, the following result shows in `bt`:
```

#5  0x00007f322b8ca7b3 in PyEval_RestoreThread (tstate=0x555751cfc240) at ../Python/ceval.c:369
#6  0x0000555751887e6c in uwsgi_python_master_fixup ()
#7  0x0000555751844b06 in uwsgi_respawn_worker ()
#8  0x0000555751842fef in master_loop ()
#9  0x0000555751880eca in uwsgi_run ()
#10 0x000055575182dd1e in main ()
```

**Comment by aqeelat** [comment]
Is it safe to upgrade to this version? I have the same env as OP.

**Comment by MikeVL** [comment]
Possible same error with dnspython v2.30

```
Traceback (most recent call last):
  File "/opt/elec/src/elec/wsgi.py", line 13, in <module>
    import sentry_sdk  # noqa
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/__init__.py", line 1, in <module>
    from sentry_sdk.hub import Hub, init
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/hub.py", line 9, in <module>
    from sentry_sdk.scope import Scope
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/scope.py", line 7, in <module>
    from sentry_sdk.utils import logger, capture_internal_exceptions
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/utils.py", line 959, in <module>
    HAS_REAL_CONTEXTVARS, ContextVar = _get_contextvars()
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/utils.py", line 929, in _get_contextvars
    if not _is_contextvars_broken():
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/utils.py", line 890, in _is_contextvars_broken
    from eventlet.patcher import is_monkey_patched  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/usr/local/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/usr/local/lib/python3.10/site-packages/eventlet/green/socket.py", line 21, in <module>
    from eventlet.support import greendns
  File "/usr/local/lib/python3.10/site-packages/eventlet/support/greendns.py", line 66, in <module>
    setattr(dns, pkg, import_patched('dns.' + pkg))
  File "/usr/local/lib/python3.10/site-packages/eventlet/support/greendns.py", line 61, in import_patched
    return patcher.import_patched(module_name, **modules)
  File "/usr/local/lib/python3.10/site-packages/eventlet/patcher.py", line 132, in import_patched
    return inject(
  File "/usr/local/lib/python3.10/site-packages/eventlet/patcher.py", line 109, in inject
    module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
  File "/usr/local/lib/python3.10/site-packages/dns/zone.py", line 86, in <module>
    class Zone(dns.transaction.TransactionManager):
  File "/usr/local/lib/python3.10/site-packages/dns/zone.py", line 757, in Zone
    ) -> dns.rdtypes.ANY.SOA.SOA:
AttributeError: module 'dns.rdtypes' has no attribute 'ANY'
```

**Comment by matejseykora** [comment]
same error with dnspython v2.30 here

**Comment by cfculhane** [comment]
The `dnspython` issue is due to `eventlet` not supporting `dnspython == 2.3.0` , see https://github.com/eventlet/eventlet/issues/781

**Comment by antonpirker** [comment]
Hey @firaskafri !

I put this on my plate and will have a look as soon I have finished my current tasks.

**Comment by antonpirker** [comment]
Hey @firaskafri ! I have now tried to reproduce this, but had no luck. (works with 1.12.1 and 1.130.0)

I created a Dockerfile for a Django application and used this command in the Dockerfile to start uWSGI:
```
CMD ["uwsgi", "--http", ":8000", "--threads", "--max-request=10", "--module", "project.wsgi"]
```

Could you provide a minimal demo project, where I can reproduce this?

The minimum information I need:
- what versions of what packages do you have installed (output of `pip list`)
- your Dockerfile
- How you start your Docker container.

**Comment by atsuoishimoto** [comment]
Here's some additional details:

### Dockerfile

```yml
FROM python:3.10.8-slim-bullseye

RUN mkdir -p /usr/src/app && mkdir /log

WORKDIR /usr/src/app

COPY pyproject.toml /usr/src/app/
COPY poetry.lock /usr/src/app/

RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        libmariadb-dev libyaml-dev libffi-dev && \
    buildDeps="make gcc g++ libc-dev gdb procps strace lsof" && \
    apt-get install -y --no-install-recommends $buildDeps && \
    pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev --no-root

COPY . /usr/src/app

EXPOSE 8000

CMD ["uwsgi", "uwsgi.ini"]
```

### docker-compose.yml

```yml
version: "2.4"
services:
  nginx:
    image: nginx:stable
    depends_on:
      - webapp
    volumes:
      - "/var/app/current/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/var/log/nginx/healthd:/var/log/nginx/healthd"
    mem_limit: 64m
    network_mode: "host"
    extra_hosts:
      - webapp:127.0.0.1
      
  webapp:
    image: imgagename
    mem_reservation: 768m
    network_mode: "host"
    extra_hosts:
      - log-sender:127.0.0.1
    environment:
      DJANGO_SETTINGS_MODULE: testapp.settings
      APP_VERSION: xxxxx
    env_file:
      - .env
    read_only: false
    user: root
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"
```

### wsgi.ini

```ini
[uwsgi]
strict=true

socket = 0.0.0.0:8000
listen=25

chdir=/usr/src/app/testapp/
module=testapp.wsgi

processes=2
threads=8

reload-on-rss=320
evil-reload-on-rss=360

threads-stacksize=2048
post-buffering=8192
buffer-size=32768
reuse-port=true
thunder-lock=true
```

### Sentry config

```python
sentry_logging = LoggingIntegration(
    level=logging.INFO,  # Capture info and above as breadcrumbs
    event_level=logging.WARNING,  # Send errors as events
)
sentry_sdk.init(
    integrations=[sentry_logging],
    release=APP_VERSION,
    environment="development",
    dsn=SENTRY_DSN,
    _experiments={
        "profiles_sample_rate": 0.001,
    },
)
```

### List of installed Python packages

```
asgiref              3.5.2
attrs                22.2.0
build                0.10.0
CacheControl         0.12.11
certifi              2022.12.7
cffi                 1.15.1
charset-normalizer   3.1.0
cleo                 2.0.1
crashtest            0.4.1
cryptography         39.0.2
distlib              0.3.6
Django               4.1.7
dulwich              0.21.3
filelock             3.9.1
html5lib             1.1
idna                 3.4
importlib-metadata   6.0.0
installer            0.6.0
jaraco.classes       3.2.3
jeepney              0.8.0
jsonschema           4.17.3
keyring              23.13.1
lockfile             0.12.2
more-itertools       9.1.0
msgpack              1.0.5
packaging            23.0
pexpect              4.8.0
pip                  22.2.2
pkginfo              1.9.6
platformdirs         2.6.2
poetry               1.4.0
poetry-core          1.5.1
poetry-plugin-export 1.3.0
ptyprocess           0.7.0
pycparser            2.21
pyproject_hooks      1.0.0
pyrsistent           0.19.3
rapidfuzz            2.13.7
requests             2.28.2
requests-toolbelt    0.10.1
SecretStorage        3.3.3
sentry-sdk           0.12.1
setuptools           63.2.0
shellingham          1.5.0.post1
six                  1.16.0
sqlparse             0.4.3
tomli                2.0.1
tomlkit              0.11.6
trove-classifiers    2023.3.9
urllib3              1.26.14
uWSGI                2.0.21
virtualenv           20.21.0
webencodings         0.5.1
wheel                0.38.4
zipp                 3.15.0
```

### Back trace of frozen process

```
0x00007f45a04cead8 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x00007f45a04cead8 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f459fd3c40f in ?? () from /usr/local/lib/libpython3.10.so.1.0
#2  0x00007f459fd5e3c2 in PyEval_RestoreThread () from /usr/local/lib/libpython3.10.so.1.0
#3  0x00005612a7477ad8 in uwsgi_python_master_fixup ()
#4  0x00005612a743027e in uwsgi_respawn_worker ()
#5  0x00005612a7469a4e in uwsgi_start ()
#6  0x00005612a746c4fb in uwsgi_setup ()
#7  0x00005612a7419de9 in main ()
```

### Wsgi log

The worker process(PID=12) is frozen just after uwsgi started. I see no suspicious messages.

```
webapp_1  | [pid: 8|app: 0|req: 7/7] 10.81.33.121 () {34 vars in 419 bytes} [Wed Mar 15 17:23:40 2023] GET /healthcheck => generated 0 bytes in 5 msecs (HTTP/1.1 200) 1 headers in 59 bytes (1 switches on core 1)
current_webapp_1 exited with code 137
webapp_1  | Python main interpreter initialized at 0x5651027bbd80
webapp_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
webapp_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
webapp_1  | threads stack size set to 2048k
webapp_1  | python threads support enabled
webapp_1  | your server socket listen backlog is limited to 25 connections
webapp_1  | your mercy for graceful operations on workers is 60 seconds
webapp_1  | mapped 1323072 bytes (1292 KB) for 16 cores
webapp_1  | *** Operational MODE: preforking+threaded ***
webapp_1  | WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5651027bbd80 pid: 1 (default app)
webapp_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
webapp_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
webapp_1  | *** uWSGI is running in multiple interpreter mode ***
webapp_1  | spawned uWSGI master process (pid: 1)
webapp_1  | spawned uWSGI worker 1 (pid: 9, cores: 8)
webapp_1  | spawned uWSGI worker 2 (pid: 12, cores: 8)
webapp_1  | Wed Mar 15 17:23:41 2023 - mem-collector thread started for worker 1
webapp_1  | 2023-03-15 17:23:43,704 healthcheck.views:views.py:20 INFO [pslog] ppid: 1 pid: 9 tid: 13 path: /healthcheck
webapp_1  | F   UID   PID  PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
webapp_1  | 4     0     1     0  20   0 117536 35852 SyS_ep Ssl  ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     1     0  20   0 117536 35852 core_s Ssl  ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 -      Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 hrtime Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 -      Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 -      Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 -      Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 -      Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 SyS_ep Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 -      Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0     9     1  20   0 526140 30432 -      Sl   ?          0:00 uwsgi uwsgi.ini
webapp_1  | 1     0    12     1  20   0 117536 24980 -      S    ?          0:00 uwsgi uwsgi.ini
webapp_1  | 0     0    19     9  20   0   8568  3100 -      R    ?          0:00 ps axlTH
webapp_1  | 
webapp_1  | [pid: 9|app: 0|req: 1/1] 127.0.0.1 () {32 vars in 357 bytes} [Wed Mar 15 17:23:43 2023] GET /healthcheck => generated 0 bytes in 11 msecs (HTTP/1.1 200) 1 headers in 59 bytes (1 switches on core 2)
webapp_1  | 2023-03-15 17:23:46,107 healthcheck.views:views.py:20 INFO [pslog] ppid: 1 pid: 9 tid: 16 path: /healthcheck
```

**Comment by atsuoishimoto** [comment]
As @firaskafri reported, a new uwsgi worker hungs at start-up at low rate. Repeating `docker-compose up` and `down` for many times may reproduces the issue. 

> The low reproduction rate (1/100) might also be related to the low sampling rate.

In out test, setting profiles_sample_rate to 1.0 did not change the reproduction rate.

**Comment by Zylphrex** [comment]
@atsuoishimoto thanks for the information, I'll take a look if I can reproduce this. One thing that may be worth trying is to upgrade to 1.16.0 as there were some changes around how the profiler is started that may address this.

**Comment by atsuoishimoto** [comment]
@Zylphrex Thank you. I could not manage to reproduce the issue with 1.17.0.

**Comment by Zylphrex** [comment]
Great! Going to close this issue then 😄
